version: '3.3'

# Names our volume
volumes:
  mysql-volume:
services:
  db:
    image: mysql
    container_name: mysql
    network_mode: bridge
    restart: always
    env_file:
      - mysql-variables.env
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - mysql-volume:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    network_mode: bridge
    links:
       - db
    ports:
      - 420:80
    environment:
      - PMA_HOST=db
